name: Angular_DockerImage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  angular_deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node.js 20.x
        uses: actions/setup-node@v1
        with:
          node-version: 20.x
          
      - name: npm install
        run: npm ci

      - name: build
        run: npm run build
        
      - name: list
        run: ls -R dist

      - name: docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      # --- ESTE ES EL PASO QUE TE FALTABA ---
      - name: Download and run the Docker base image
        run: docker run -d --name http_base httpd

      - name: copy model to the Docker image
        run: docker cp dist/lifegoals/browser/. http_base:/usr/local/apache2/htdocs

      - name: Build the custom Docker image
        run: |
         docker commit --change "ENV MODEL_NAME http_base" http_base ${{secrets.DOCKER_USER}}/lifegoals:${{ github.sha }}
         docker tag ${{secrets.DOCKER_USER}}/lifegoals:${{ github.sha }} ${{secrets.DOCKER_USER}}/lifegoals:latest
      - name: Docker Push
        run: |
          docker push ${{secrets.DOCKER_USER}}/lifegoals:${{ github.sha }}
          docker push ${{secrets.DOCKER_USER}}/lifegoals:latest

      - name: Trigger Render Deploy
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
